export const CONSTANTS = {
    GENDER: 'gender',
    STATUS: 'status',
    ALL: 'all',
    SURVIVED: 'SURVIVED',
    NOT_SURVIVED: 'NOT SURVIVED',
    N_A: 'N/A',
    TICKET_LABEL: 'ticket: ',
    AGE_LABEL: 'age',
    TICKET_TEXT: 'ticket',
    NAME_TEXT: 'name',
    STATUS_TEXT: 'status',
    GENDER_TEXT: 'gender',
    SURVIVED_TEXT: 'SURVIVED',
    NOT_SURVIVED_TEXT: 'NOT SURVIVED',
    BASE_URL: 'https://raw.githubusercontent.com/altkraft/for-applicants/master/frontend/titanic/passengers.json',
    ERROR_LOADING_DATA: 'Не удалось загрузить данные о пассажирах. Пожалуйста, попробуйте позже.',
    HTTP_ERROR_MESSAGE: 'HTTP Error: ',
    SENTINEL_FLEX_DISPLAY: 'flex',
    SENTINEL_NONE_DISPLAY: 'none',
};